// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 * Generated by: hibernate/HibernateEntityImpl.vsl in andromda-hibernate-cartridge.
 */
package org;

/**
 * @see Class1
 */
// HibernateEntityImpl.vsl annotations merge-point
public class Class1Impl
    extends Class1
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4908477076326881609L;

    /**
     * @see Class1#compute()
     */
    @Override
    public long compute()
    {
        // TODO implement public long compute()
        long rtn = 0;
        return rtn;
    }

// HibernateEntityImpl.vsl merge-point
}